#!/usr/bin/env python3
"""
remove_channel.py - remove a channel from sheikhs.json and the prefetched files.

Created by Ali Zaghloul on 26/09/2026.

Takes the UC id the Worker already resolved (or one typed into the GitHub Actions
form), drops it from sheikhs.json, deletes channels/<id>.json and filters the entry
out of channels/index.json. A channel that is not listed is left alone and the run
still succeeds, so the workflow is safe to re-run.

Spends ZERO YouTube quota and makes no network call at all: every fact it needs is
already committed, and the surviving entries in channels/index.json are already
correct, so the index is filtered rather than regenerated by prefetch.py.

Reads : INPUT_CHANNEL, INPUT_CONFIRM (env), sheikhs.json, channels/index.json
Writes: sheikhs.json, channels/index.json; deletes channels/<channelId>.json

Quota: 0 units.

Python 3 standard library only.
"""

import json
import os
import sys

from add_channel import (
    SHEIKHS_PATH,
    _CHANNEL_ID_RE,
    as_str,
    git_diff_stat,
    log,
    set_step_output,
    today_utc,
    write_sheikhs,
)
from prefetch import CHANNELS_DIR, write_json

# The exact word the dispatch must echo back. Reaching this script deletes data, so
# the confirmation is required even on the hand-dispatch path, where no Worker has
# already asked twice.
CONFIRM_WORD = "REMOVE"


def read_json(path):
    """The parsed file, or None when it is missing or unreadable."""
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except FileNotFoundError:
        return None
    except (OSError, ValueError) as exc:  # noqa: BLE001 - reported, never raised
        log("ERROR: could not read %s (%s)" % (path, exc))
        return None


def one_line(value):
    """A value safe to write into $GITHUB_OUTPUT, which is newline-delimited."""
    return as_str(value).replace("\r", " ").replace("\n", " ")


def main():
    confirm = os.environ.get("INPUT_CONFIRM", "").strip()
    if confirm != CONFIRM_WORD:
        log("ERROR: INPUT_CONFIRM must be exactly %r to delete anything" % CONFIRM_WORD)
        return 1

    channel_id = os.environ.get("INPUT_CHANNEL", "").strip()
    if not channel_id:
        log("ERROR: INPUT_CHANNEL is not set - paste the UC id of the channel to remove")
        return 1

    # Only a canonical id is accepted. The web page resolves a URL, @handle or name to
    # an id before dispatching, so the id echoed to the user and the id deleted here
    # are the same value by construction.
    if not _CHANNEL_ID_RE.match(channel_id):
        log("ERROR: %r is not a channel id - expected UC followed by 22 characters"
            % channel_id)
        return 1

    sheikhs = read_json(SHEIKHS_PATH)
    if not isinstance(sheikhs, dict) or not isinstance(sheikhs.get("channels"), list):
        log("ERROR: sheikhs.json is missing or malformed - nothing removed")
        return 1

    kept = []
    removed_names = []
    for entry in sheikhs["channels"]:
        if isinstance(entry, dict) and as_str(entry.get("id")) == channel_id:
            removed_names.append(as_str(entry.get("name")))
            continue
        kept.append(entry)

    if not removed_names:
        # Not an error: re-running an already-applied removal must still succeed.
        log("Channel %s is not in sheikhs.json - nothing to remove" % channel_id)
        set_step_output("removed", "false")
        return 0

    if len(removed_names) > 1:
        log("Note: %d entries shared this id; all were removed" % len(removed_names))

    name = removed_names[0]
    log("Removing %s (%s)" % (name or "(no name)", channel_id))

    sheikhs["channels"] = kept
    sheikhs["updatedAt"] = today_utc()
    size = write_sheikhs(SHEIKHS_PATH, sheikhs)
    log("sheikhs.json : %d channels, %d bytes" % (len(kept), size))

    # channels/<id>.json is generated, so deleting it is safe. prefetch.py has no
    # delete path of its own, so a file left behind would stay publicly fetchable by
    # direct URL forever even after the channel is gone from every index.
    channel_path = os.path.join(CHANNELS_DIR, channel_id + ".json")
    if os.path.exists(channel_path):
        os.remove(channel_path)
        log("deleted      : channels/%s.json" % channel_id)
    else:
        log("channels/%s.json was already absent" % channel_id)

    # The surviving entries are already correct on disk, so the index is filtered
    # instead of regenerated. Regenerating means re-running prefetch.py: roughly 740
    # YouTube quota units to rediscover facts already committed.
    index_path = os.path.join(CHANNELS_DIR, "index.json")
    index = read_json(index_path)
    if isinstance(index, dict) and isinstance(index.get("channels"), list):
        before = len(index["channels"])
        index["channels"] = [
            entry for entry in index["channels"]
            if not (isinstance(entry, dict) and as_str(entry.get("id")) == channel_id)
        ]
        # generatedAt is deliberately left untouched: it records when the surviving
        # entries were fetched, and that is still true of every one of them.
        index_size = write_json(index_path, index)
        log("index.json   : %d -> %d channels, %d bytes"
            % (before, len(index["channels"]), index_size))
    else:
        log("WARNING: channels/index.json is missing or malformed - left untouched")

    git_diff_stat(SHEIKHS_PATH)
    git_diff_stat(CHANNELS_DIR)
    set_step_output("removed", "true")
    set_step_output("name", one_line(name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
